version: "3.9"


networks:
  local:
    driver: bridge

volumes:
  project:

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#    command: "./prestart.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - local